---
abstract: 'Detailed information about Map::Metro::Plugin::Map::%s'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::NoTabs: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, Dist::Iller version 0.1002, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MapMetro-MakeLinePod
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: '5.000'
  List::AllUtils: '0'
  Map::Metro: '0.2100'
  Moose: '2.0000'
  Path::Tiny: '0'
  Types::Standard: '0'
  namespace::sweep: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/Csson/p5-Dist-Zilla-Plugin-MapMetro-MakeLinePod/issues
  homepage: https://github.com/Csson/p5-Dist-Zilla-Plugin-MapMetro-MakeLinePod
  repository: https://github.com/Csson/p5-Dist-Zilla-Plugin-MapMetro-MakeLinePod.git
version: '0.1001'
